app_name            = "app-hybrid-christmas-api"
location            = "westeurope"
resource_group_name = "rg-hybrid-christmas"
service_plan_id     = "your-service-plan-id-goes-here"
source_tag          = "Hybrid.Christmas"