app_name                        = "app-hybrid-christmas-api"
location                        = "westeurope"
northpole_hostname              = "elvesapi.northpole.christmas"
northpole_hostport              = "443"
relay_name                      = "sb-northpole"
resource_group_name             = "rg-hybrid-christmas"
service_plan_id                 = "your-service-plan-id-goes-here"
source_tag                      = "Hybrid.Christmas"